name: Testing
run-name: ${{ github.actor }} push in .github new version
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
#hd
      - name: Clone test
        run: |
          git clone https://github.com/Claucdan/Test-for-vector

      - name: Clone googletest
        run: |
          git clone https://github.com/google/googletest ${{github.workspace}}/Test-for-vector

      - name: Configure Test
        run: |
          cd   ${{github.workspace}}/Test-for-vector
          cmake -S . -B ${{github.workspace}}/Test-for-vector

      - name: Build Test
        # Build your program with the given configuration
        run:  cmake --build ${{github.workspace}}/Test-for-vector -j 12

      - name: Testing
        run:  ctest --test-dir ${{github.workspace}}/Test-for-vector --output-on-failure -j12

      - name: Result
        run: echo All work!!!